---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wyc.
--- DateTime: 2023/12/22 下午8:40
---
local redisKey = KEYS[1] -- 第1个KEYS为redisKey
local versionKey = KEYS[2] -- 第2个KEYS为version值的field
local localVersion = ARGV[1] -- 第1个ARGV为当前version值
local newVersion = ARGV[2] -- 第2个ARGV为新的version值（lua只有到秒的精度，只能外面传进去一个了）
local remoteVersion = redis.call('HGET', redisKey, versionKey)
if localVersion == remoteVersion or (ARGV[3] and not current) -- 如果是空也可以set
then
    for i = 3, #(KEYS) do
        -- 第3个KEYS开始为要修改的field
        redis.call("HSET", redisKey, KEYS[i], ARGV[i])
    end
    redis.call('HSET', redisKey, versionKey, newVersion)
    return true
end
return false