logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

vpn:
  config: classpath:aws-vpn.json


prefix:
  api: "/api"

  ws:
    application.destination: "/ws"
    user.destination: "/user"
    endpoint:
      websocket: "/websocket"
      sockjs: "/sockjs"

  resources:
    static: "/static"
    bgs:
      static: "/front"
      web: "/bgs"