logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
#    org.springframework.boot.autoconfigure: DEBUG

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

vpn:
  config: classpath:aws-vpn.json


prefix:
  api: "/api"

  ws:
    application.destination: "/bgs" # 这个可以和bgs.web相同，是因为这个走的是ws的长链接，不是路由了
    user.destination: "/user"
    endpoint:
      websocket: "/websocket"
      sockjs: "/sockjs"
    channels:
      chat: "/private/chat"
      room: "/private/room"

  resources:
    static: "/static"
    bgs:
      static: "/front"
      web: "/bgs"


